version: '3.7' 
services: 
  server: 
    build: ./server
    ports: 
      - 42598:3000
  client: 
    build: ./client
    ports: 
      - 42150:80
    environment:
      - url=http://server:42598
    depends_on: 
      - server     